delete from medicine_lookup;
insert into medicine_lookup (order_number, name) values(100,"Abilify");
insert into medicine_lookup (order_number, name) values(101,"Abilify Discmelt");
insert into medicine_lookup (order_number, name) values(102,"acyclovir");
insert into medicine_lookup (order_number, name) values(103,"Adderall");
insert into medicine_lookup (order_number, name) values(104,"Advair");
insert into medicine_lookup (order_number, name) values(105,"Advil");
insert into medicine_lookup (order_number, name) values(106,"Afrin");
insert into medicine_lookup (order_number, name) values(107,"albuterol");
insert into medicine_lookup (order_number, name) values(108,"Aleve");
insert into medicine_lookup (order_number, name) values(109,"alprazolam");
insert into medicine_lookup (order_number, name) values(110,"Alzheimer's Disease - Cholinesterase Inhibitors");
insert into medicine_lookup (order_number, name) values(111,"Alzheimer's Disease - NMDA Receptor Antagonists");
insert into medicine_lookup (order_number, name) values(112,"amantadine");
insert into medicine_lookup (order_number, name) values(113,"Ambien");
insert into medicine_lookup (order_number, name) values(114,"Ambien CR");
insert into medicine_lookup (order_number, name) values(115,"amitriptyline");
insert into medicine_lookup (order_number, name) values(116,"amoxicillin");
insert into medicine_lookup (order_number, name) values(117,"amphetamine, Adderall XR");
insert into medicine_lookup (order_number, name) values(118,"ampicillin");
insert into medicine_lookup (order_number, name) values(119,"Anafranil");
insert into medicine_lookup (order_number, name) values(120,"Aricept");
insert into medicine_lookup (order_number, name) values(121,"aripiprazole");
insert into medicine_lookup (order_number, name) values(122,"Armour Thyroid");
insert into medicine_lookup (order_number, name) values(123,"arnica");
insert into medicine_lookup (order_number, name) values(124,"Aspirin");
insert into medicine_lookup (order_number, name) values(125,"atenolol");
insert into medicine_lookup (order_number, name) values(126,"Ativan");
insert into medicine_lookup (order_number, name) values(127,"atomoxetine");
insert into medicine_lookup (order_number, name) values(128,"azithromycin");
insert into medicine_lookup (order_number, name) values(129,"Bayer");
insert into medicine_lookup (order_number, name) values(130,"benztropine mesylate");
insert into medicine_lookup (order_number, name) values(131,"Biaxin");
insert into medicine_lookup (order_number, name) values(132,"birth control");
insert into medicine_lookup (order_number, name) values(133,"bupropion");
insert into medicine_lookup (order_number, name) values(134,"BuSpar");
insert into medicine_lookup (order_number, name) values(135,"buspirone");
insert into medicine_lookup (order_number, name) values(136,"carbamazepine");
insert into medicine_lookup (order_number, name) values(137,"carbidopa");
insert into medicine_lookup (order_number, name) values(138,"Celexa");
insert into medicine_lookup (order_number, name) values(139,"Chantix");
insert into medicine_lookup (order_number, name) values(140,"chloral hydrate");
insert into medicine_lookup (order_number, name) values(141,"chlorpromazine");
insert into medicine_lookup (order_number, name) values(142,"Cialis");
insert into medicine_lookup (order_number, name) values(143,"citalopram");
insert into medicine_lookup (order_number, name) values(144,"Claritin");
insert into medicine_lookup (order_number, name) values(145,"clindamycin");
insert into medicine_lookup (order_number, name) values(146,"clomipramine");
insert into medicine_lookup (order_number, name) values(147,"clonazepam");
insert into medicine_lookup (order_number, name) values(148,"clonidine");
insert into medicine_lookup (order_number, name) values(149,"clorazepate");
insert into medicine_lookup (order_number, name) values(150,"clozapine");
insert into medicine_lookup (order_number, name) values(151,"Clozaril");
insert into medicine_lookup (order_number, name) values(152,"Cogentin");
insert into medicine_lookup (order_number, name) values(153,"Compazine");
insert into medicine_lookup (order_number, name) values(154,"Concerta");
insert into medicine_lookup (order_number, name) values(155,"Coumadin");
insert into medicine_lookup (order_number, name) values(156,"Crestor");
insert into medicine_lookup (order_number, name) values(157,"Cymbalta");
insert into medicine_lookup (order_number, name) values(158,"Darvocet");
insert into medicine_lookup (order_number, name) values(159,"Daytrana");
insert into medicine_lookup (order_number, name) values(160,"Demerol");
insert into medicine_lookup (order_number, name) values(161,"Depakote");
insert into medicine_lookup (order_number, name) values(162,"Depakote ER");
insert into medicine_lookup (order_number, name) values(163,"desipramine");
insert into medicine_lookup (order_number, name) values(164,"Dexedrine");
insert into medicine_lookup (order_number, name) values(165,"dextroamphetamine");
insert into medicine_lookup (order_number, name) values(166,"diazepam");
insert into medicine_lookup (order_number, name) values(167,"Diflucan");
insert into medicine_lookup (order_number, name) values(168,"Dilantin");
insert into medicine_lookup (order_number, name) values(169,"Dilaudid");
insert into medicine_lookup (order_number, name) values(170,"donepezil");
insert into medicine_lookup (order_number, name) values(171,"doxepin");
insert into medicine_lookup (order_number, name) values(172,"Effexor");
insert into medicine_lookup (order_number, name) values(173,"Effexor XR");
insert into medicine_lookup (order_number, name) values(174,"Elavil");
insert into medicine_lookup (order_number, name) values(175,"Eldepryl");
insert into medicine_lookup (order_number, name) values(176,"escitalopram");
insert into medicine_lookup (order_number, name) values(177,"estradiol");
insert into medicine_lookup (order_number, name) values(178,"eszopiclone");
insert into medicine_lookup (order_number, name) values(179,"Exelon");
insert into medicine_lookup (order_number, name) values(180,"Exelon Patch");
insert into medicine_lookup (order_number, name) values(181,"fentanyl");
insert into medicine_lookup (order_number, name) values(182,"fexofenadine");
insert into medicine_lookup (order_number, name) values(183,"Fioricet");
insert into medicine_lookup (order_number, name) values(184,"Fiorinal");
insert into medicine_lookup (order_number, name) values(185,"fish oil");
insert into medicine_lookup (order_number, name) values(186,"Flexeril");
insert into medicine_lookup (order_number, name) values(187,"Flomax");
insert into medicine_lookup (order_number, name) values(188,"Flonase");
insert into medicine_lookup (order_number, name) values(189,"fluconazole");
insert into medicine_lookup (order_number, name) values(190,"fluoxetine");
insert into medicine_lookup (order_number, name) values(191,"fluphenazine");
insert into medicine_lookup (order_number, name) values(192,"fluvoxamine");
insert into medicine_lookup (order_number, name) values(193,"Focalin");
insert into medicine_lookup (order_number, name) values(194,"Fosamax");
insert into medicine_lookup (order_number, name) values(195,"gabapentin");
insert into medicine_lookup (order_number, name) values(196,"Gabitril");
insert into medicine_lookup (order_number, name) values(197,"galantamine");
insert into medicine_lookup (order_number, name) values(198,"Geodon");
insert into medicine_lookup (order_number, name) values(199,"ginkgo biloba");
insert into medicine_lookup (order_number, name) values(200,"guaifenesin");
insert into medicine_lookup (order_number, name) values(301,"guanfacine");
insert into medicine_lookup (order_number, name) values(302,"Halcion");
insert into medicine_lookup (order_number, name) values(303,"Haldol");
insert into medicine_lookup (order_number, name) values(304,"haloperidol");
insert into medicine_lookup (order_number, name) values(305,"hydrocodone");
insert into medicine_lookup (order_number, name) values(306,"hydromorphone");
insert into medicine_lookup (order_number, name) values(307,"ibuprofen");
insert into medicine_lookup (order_number, name) values(308,"imipramine");
insert into medicine_lookup (order_number, name) values(309,"Imitrex");
insert into medicine_lookup (order_number, name) values(310,"insulin - injectable combinations");
insert into medicine_lookup (order_number, name) values(311,"insulin - injectable intermediate/long-acting");
insert into medicine_lookup (order_number, name) values(312,"insulin - injectable short/rapid-acting");
insert into medicine_lookup (order_number, name) values(313,"Invega");
insert into medicine_lookup (order_number, name) values(314,"Keflex");
insert into medicine_lookup (order_number, name) values(315,"Klonopin");
insert into medicine_lookup (order_number, name) values(316,"Klonopin Wafer");
insert into medicine_lookup (order_number, name) values(317,"Lamictal");
insert into medicine_lookup (order_number, name) values(318,"Lamictal CD");
insert into medicine_lookup (order_number, name) values(319,"Lamictal ODT");
insert into medicine_lookup (order_number, name) values(320,"Lamictal XR");
insert into medicine_lookup (order_number, name) values(321,"lamotrigine");
insert into medicine_lookup (order_number, name) values(322,"Lantus");
insert into medicine_lookup (order_number, name) values(323,"Levaquin");
insert into medicine_lookup (order_number, name) values(324,"levodopa");
insert into medicine_lookup (order_number, name) values(325,"levothyroxine");
insert into medicine_lookup (order_number, name) values(326,"Levoxyl");
insert into medicine_lookup (order_number, name) values(327,"Lexapro");
insert into medicine_lookup (order_number, name) values(328,"Librium");
insert into medicine_lookup (order_number, name) values(329,"Lipitor");
insert into medicine_lookup (order_number, name) values(330,"lisinopril");
insert into medicine_lookup (order_number, name) values(331,"lithium");
insert into medicine_lookup (order_number, name) values(332,"Lomotil");
insert into medicine_lookup (order_number, name) values(333,"lorazepam");
insert into medicine_lookup (order_number, name) values(334,"lovastatin");
insert into medicine_lookup (order_number, name) values(335,"Lunesta");
insert into medicine_lookup (order_number, name) values(336,"Luvox");
insert into medicine_lookup (order_number, name) values(337,"Luvox CR");
insert into medicine_lookup (order_number, name) values(338,"marijuana");
insert into medicine_lookup (order_number, name) values(339,"melatonin");
insert into medicine_lookup (order_number, name) values(340,"Mellaril");
insert into medicine_lookup (order_number, name) values(341,"memantine");
insert into medicine_lookup (order_number, name) values(342,"metformin");
insert into medicine_lookup (order_number, name) values(343,"methadone");
insert into medicine_lookup (order_number, name) values(344,"methylphenidate");
insert into medicine_lookup (order_number, name) values(345,"metoprolol");
insert into medicine_lookup (order_number, name) values(346,"metronidazole");
insert into medicine_lookup (order_number, name) values(347,"Midrin");
insert into medicine_lookup (order_number, name) values(348,"mirtazapine");
insert into medicine_lookup (order_number, name) values(349,"modafinil");
insert into medicine_lookup (order_number, name) values(350,"Namenda");
insert into medicine_lookup (order_number, name) values(351,"naproxen");
insert into medicine_lookup (order_number, name) values(352,"Nardil");
insert into medicine_lookup (order_number, name) values(353,"Nasacort AQ");
insert into medicine_lookup (order_number, name) values(354,"Nasacort HFA");
insert into medicine_lookup (order_number, name) values(355,"Nasonex");
insert into medicine_lookup (order_number, name) values(356,"nefazodone");
insert into medicine_lookup (order_number, name) values(357,"Neurontin");
insert into medicine_lookup (order_number, name) values(358,"Norpramin");
insert into medicine_lookup (order_number, name) values(359,"nortriptyline");
insert into medicine_lookup (order_number, name) values(360,"olanzapine");
insert into medicine_lookup (order_number, name) values(361,"omega-3 fatty acid");
insert into medicine_lookup (order_number, name) values(362,"omeprazole");
insert into medicine_lookup (order_number, name) values(363,"oxcarbazepine");
insert into medicine_lookup (order_number, name) values(364,"Oxycodan");
insert into medicine_lookup (order_number, name) values(365,"oxycodone");
insert into medicine_lookup (order_number, name) values(366,"OxyContin");
insert into medicine_lookup (order_number, name) values(367,"Pamelor");
insert into medicine_lookup (order_number, name) values(368,"Parnate");
insert into medicine_lookup (order_number, name) values(369,"paroxetine");
insert into medicine_lookup (order_number, name) values(370,"Patanol");
insert into medicine_lookup (order_number, name) values(371,"Paxil CR");
insert into medicine_lookup (order_number, name) values(372,"Percocet");
insert into medicine_lookup (order_number, name) values(373,"Percodan");
insert into medicine_lookup (order_number, name) values(374,"perphenazine");
insert into medicine_lookup (order_number, name) values(375,"perphenazine (in Triavil)");
insert into medicine_lookup (order_number, name) values(376,"phenelzine");
insert into medicine_lookup (order_number, name) values(377,"phenobarbital");
insert into medicine_lookup (order_number, name) values(378,"Plavix");
insert into medicine_lookup (order_number, name) values(379,"prednisone");
insert into medicine_lookup (order_number, name) values(380,"Premarin");
insert into medicine_lookup (order_number, name) values(381,"Prilosec");
insert into medicine_lookup (order_number, name) values(382,"Pristiq");
insert into medicine_lookup (order_number, name) values(383,"Prolixin");
insert into medicine_lookup (order_number, name) values(384,"Provigil");
insert into medicine_lookup (order_number, name) values(385,"Prozac");
insert into medicine_lookup (order_number, name) values(386,"quetiapine");
insert into medicine_lookup (order_number, name) values(387,"Remeron");
insert into medicine_lookup (order_number, name) values(388,"Reminyl");
insert into medicine_lookup (order_number, name) values(389,"Restoril");
insert into medicine_lookup (order_number, name) values(390,"Risperdal");
insert into medicine_lookup (order_number, name) values(391,"Risperdal Consta");
insert into medicine_lookup (order_number, name) values(392,"risperidone");
insert into medicine_lookup (order_number, name) values(393,"Ritalin");
insert into medicine_lookup (order_number, name) values(394,"Ritalin LA");
insert into medicine_lookup (order_number, name) values(395,"Ritalin SR");
insert into medicine_lookup (order_number, name) values(396,"rivastigmine");
insert into medicine_lookup (order_number, name) values(397,"Rozerem");
insert into medicine_lookup (order_number, name) values(398,"Seroquel");
insert into medicine_lookup (order_number, name) values(399,"Seroquel XR");
insert into medicine_lookup (order_number, name) values(400,"sertraline");
insert into medicine_lookup (order_number, name) values(401,"Serzone");
insert into medicine_lookup (order_number, name) values(402,"simvastatin");
insert into medicine_lookup (order_number, name) values(403,"Sinemet");
insert into medicine_lookup (order_number, name) values(404,"Sinequan");
insert into medicine_lookup (order_number, name) values(405,"Singulair");
insert into medicine_lookup (order_number, name) values(406,"Somnote");
insert into medicine_lookup (order_number, name) values(407,"Sonata");
insert into medicine_lookup (order_number, name) values(408,"Strattera");
insert into medicine_lookup (order_number, name) values(409,"Symbyax");
insert into medicine_lookup (order_number, name) values(410,"Symmetrel");
insert into medicine_lookup (order_number, name) values(411,"Tegretol");
insert into medicine_lookup (order_number, name) values(412,"Tegretol XR");
insert into medicine_lookup (order_number, name) values(413,"temazepam");
insert into medicine_lookup (order_number, name) values(414,"Tenex");
insert into medicine_lookup (order_number, name) values(415,"tiagabine");
insert into medicine_lookup (order_number, name) values(416,"Tofranil");
insert into medicine_lookup (order_number, name) values(417,"Topamax");
insert into medicine_lookup (order_number, name) values(418,"topiramate");
insert into medicine_lookup (order_number, name) values(419,"tramadol");
insert into medicine_lookup (order_number, name) values(420,"Tranxene");
insert into medicine_lookup (order_number, name) values(421,"tranylcypromine");
insert into medicine_lookup (order_number, name) values(422,"trazodone");
insert into medicine_lookup (order_number, name) values(423,"Triavil");
insert into medicine_lookup (order_number, name) values(424,"Trileptal");
insert into medicine_lookup (order_number, name) values(425,"Ultram");
insert into medicine_lookup (order_number, name) values(426,"valacyclovir");
insert into medicine_lookup (order_number, name) values(427,"valproic acid");
insert into medicine_lookup (order_number, name) values(428,"Valtrex");
insert into medicine_lookup (order_number, name) values(429,"verapamil");
insert into medicine_lookup (order_number, name) values(430,"Vicodin");
insert into medicine_lookup (order_number, name) values(431,"vitamin A");
insert into medicine_lookup (order_number, name) values(432,"vitamin C");
insert into medicine_lookup (order_number, name) values(433,"vitamin D");
insert into medicine_lookup (order_number, name) values(434,"vitamin E");
insert into medicine_lookup (order_number, name) values(435,"vitamin K");
insert into medicine_lookup (order_number, name) values(436,"Vitamins");
insert into medicine_lookup (order_number, name) values(437,"Vytorin");
insert into medicine_lookup (order_number, name) values(438,"Vyvanse");
insert into medicine_lookup (order_number, name) values(439,"warfarin");
insert into medicine_lookup (order_number, name) values(440,"Wellbutrin");
insert into medicine_lookup (order_number, name) values(441,"Wellbutrin SR");
insert into medicine_lookup (order_number, name) values(442,"Wellbutrin XL");
insert into medicine_lookup (order_number, name) values(443,"Xanax");
insert into medicine_lookup (order_number, name) values(444,"Xanax XR");
insert into medicine_lookup (order_number, name) values(445,"zaleplon");
insert into medicine_lookup (order_number, name) values(446,"Zantac");
insert into medicine_lookup (order_number, name) values(447,"ziprasidone");
insert into medicine_lookup (order_number, name) values(448,"Zocor");
insert into medicine_lookup (order_number, name) values(449,"Zoloft");
insert into medicine_lookup (order_number, name) values(450,"zolpidem");
insert into medicine_lookup (order_number, name) values(451,"Zyprexa");
insert into medicine_lookup (order_number, name) values(452,"Zyrtec");
update medicine_lookup set created_date=now();